<a href="https://colab.research.google.com/github/ChirudeepG/CMPE-258-Assignment2/blob/main/2B_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Scalar vector multiplication

In [3]:
a = np.array([1])
b = np.array([4, 5])
mult = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(mult)

[1]
[4 5]
[4 5]


# Vector vector multiplication

In [4]:
a = np.random.randn(2, 6)
b = np.random.randn(6, 3)
mult = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

[[-0.17420637 -0.83879491 -0.66432347 -0.58547925  1.54334592 -2.25883428]
 [ 0.44860075  0.82428116 -0.31458394 -0.13210289  0.72531735 -0.01744281]]
[[ 0.50723422 -0.12419405 -1.68035287]
 [-0.43378449 -0.4413563   0.80978303]
 [-1.17833467  1.05169876 -1.17021167]
 [ 1.4193233  -0.69880103  2.15751296]
 [ 1.64730168  0.9010086   0.03761291]
 [ 1.60876479  0.71937765  0.16757439]]
[[-0.8642729  -0.13207881 -1.19276676]
 [ 1.21992882 -0.01707993  0.02115574]]


# Outer product


In [5]:
a = np.arange(8)
b = np.arange(4, 6)  
prod = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

[0 1 2 3 4 5 6 7]
[4 5]
[[ 0  0]
 [ 4  5]
 [ 8 10]
 [12 15]
 [16 20]
 [20 25]
 [24 30]
 [28 35]]


# Hadamard product

In [6]:
a = np.arange(8).reshape(2, 4)
b = np.arange(4, 12).reshape(2, 4)
prod = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  5 12 21]
 [32 45 60 77]]


# Scalar dot product

In [7]:
a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
prod = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
204


# Batch matrix multiplication

In [8]:
a = np.random.randn(3, 3, 5)
b = np.random.randn(3, 5, 2)
batch_mult = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

[[[-0.16564219 -0.54723386 -1.01665884  0.11074938  0.75599002]
  [-0.39068596  0.91081794 -1.36214324  0.30025977 -1.39266087]
  [ 0.21297227  0.01073878 -0.36712964  1.55547465  1.18195015]]

 [[-1.04827847  0.81291355 -0.72709657  1.44981231  0.24715466]
  [-1.80766552  0.63831142  0.0757464  -1.51223089 -2.90051062]
  [ 0.98581466  0.4685963   0.13069661 -0.98655869  0.24445476]]

 [[ 1.13059061  2.56200855 -0.09741261 -1.57660508 -2.627392  ]
  [-0.46122791  0.36122587 -0.58495732  0.36539343  1.97174014]
  [-0.26926747  0.31527729 -0.55313835 -0.34390386  1.03295172]]]
[[[ 1.37315986  0.14912489]
  [-1.03825918  0.11926473]
  [-2.34344252 -0.38060762]
  [-0.85026068 -1.39030563]
  [ 0.33128538 -0.97527541]]

 [[-0.27444201 -0.9716431 ]
  [ 0.11618257 -0.72910583]
  [ 0.90204282  1.42684829]
  [-1.75350418 -0.15093374]
  [ 0.05471032  1.29112309]]

 [[ 0.37711657  0.47540562]
  [-1.15953538  0.71043479]
  [-2.03842211 -0.13341756]
  [ 1.31671579 -1.09248263]
  [-1.21911405  1.1694

# Tensor reduction

In [9]:
a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


# Transpose

In [12]:
a = np.arange(8).reshape(4, 2)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]


# Bilinear transformation

In [13]:
a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

[[ 0.70124649  1.60948819  0.31722078]
 [ 0.24116532 -0.51447308 -1.53361881]]
[[[ 0.13380502 -0.36391307 -1.32604818 -0.70107411]
  [ 0.93625301 -0.6622212   0.79882163 -0.20676776]
  [ 0.24392222  0.34713821  0.37541957  0.18706691]]

 [[-0.55404409 -0.75579131  0.60487663  0.31248687]
  [ 1.01500443 -0.18676334 -1.06609955 -0.57650207]
  [ 0.18111822  0.66415499 -1.70337762 -1.98882065]]

 [[ 0.10851586 -0.00956364 -0.92037992  1.64063235]
  [-0.67035742  1.00444505 -0.99765005 -0.21074751]
  [-0.3373265  -0.48273546  0.92826361 -1.32492068]]]
[[ 0.1563591   1.37430495  1.40705664  0.29735514]
 [-0.18371616 -0.58239636  0.12502318 -1.40448724]]
[[-0.96106491 -3.62442236 -0.80830166]
 [ 0.64168313 -3.57789785 -3.99543326]]


# Attention

In [14]:
bM = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1): 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at
Y = np.random.randn(3,5,7)
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[3.48114866e-03 3.40506344e-04 8.37728025e-03 2.21285479e-02
  3.13852917e-02]
 [2.90071016e-02 6.67772636e-02 4.64269542e-01 8.62240233e-03
  2.49255168e-01]
 [3.21470840e-03 2.66820444e-03 2.93354020e-03 1.07460280e-01
  7.90138989e-05]]


# Treeqn

In [17]:
def transition(zl):
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)
zl = np.random.rand(2, 3)
b = np.random.rand(5, 3)
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[0.92065722, 1.22626795, 1.02561829],
        [1.13102881, 1.14190109, 0.88295137],
        [1.0178306 , 1.26152678, 0.93008915],
        [1.30790419, 1.17894969, 0.75090542],
        [1.16750658, 1.31851813, 1.03026076]],

       [[1.50661146, 1.37104525, 1.12629072],
        [1.60637423, 1.30166898, 1.06161207],
        [1.46959814, 1.28055049, 1.09141004],
        [1.77759582, 1.21141922, 0.85053703],
        [1.70846706, 1.40156157, 1.13235522]]])