<a href="https://colab.research.google.com/github/ChirudeepG/CMPE-258-Assignment2/blob/main/2B_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Scalar vector multiplication

In [5]:
a = torch.rand(1)
b = torch.rand(4, 6)
mult = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mult)

tensor([0.3313])
tensor([[0.4851, 0.4064, 0.8049, 0.3850, 0.0183, 0.8725],
        [0.6522, 0.7195, 0.0587, 0.8466, 0.8328, 0.6004],
        [0.6877, 0.3292, 0.2900, 0.6872, 0.4416, 0.9597],
        [0.4194, 0.1896, 0.1505, 0.1915, 0.1617, 0.4004]])
tensor([[0.1607, 0.1346, 0.2666, 0.1275, 0.0061, 0.2890],
        [0.2161, 0.2384, 0.0195, 0.2805, 0.2759, 0.1989],
        [0.2278, 0.1090, 0.0961, 0.2277, 0.1463, 0.3179],
        [0.1389, 0.0628, 0.0499, 0.0634, 0.0536, 0.1326]])


# Vector vector multiplication

In [9]:
a = torch.rand(2, 6)
b = torch.rand(6, 3)
mult = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mult)

tensor([[0.9774, 0.1520, 0.7850, 0.4123, 0.9935, 0.7522],
        [0.2617, 0.9254, 0.2538, 0.9307, 0.5132, 0.2324]])
tensor([[0.9386, 0.8450, 0.2563],
        [0.7607, 0.5866, 0.1757],
        [0.1255, 0.8354, 0.3142],
        [0.6979, 0.7214, 0.8781],
        [0.3365, 0.6935, 0.3320],
        [0.5362, 0.8716, 0.4842]])
tensor([[2.1570, 3.2130, 1.5801],
        [1.9282, 2.2059, 1.4096]])


# Scalar dot product

In [14]:
a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
prod = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


# Outer product

In [15]:
a = torch.arange(8)
b = torch.arange(4, 6)  
prod = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([4, 5])
tensor([[ 0,  0],
        [ 4,  5],
        [ 8, 10],
        [12, 15],
        [16, 20],
        [20, 25],
        [24, 30],
        [28, 35]])


# Hadamard product

In [17]:
a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
prod = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


# Batch matrix multiplication

In [21]:
a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[ 1.5254,  1.9199, -0.4792,  2.0774,  0.6855],
         [-0.5178,  0.5267,  0.2078,  0.0098,  2.3039],
         [ 1.6595,  2.9954, -0.6341, -0.1312,  0.8082]],

        [[-0.8789, -1.7089,  0.4529, -0.3293,  1.4509],
         [-0.7451,  0.0403, -0.0705,  0.4589,  1.8620],
         [ 0.2497,  0.9242, -1.9819, -0.4972,  0.9077]],

        [[ 1.3157,  0.5770, -0.9078,  1.0450,  0.1962],
         [-0.6498,  0.7053, -1.0756, -2.1783, -1.1061],
         [ 0.6627, -0.9473, -0.4753,  1.6333,  0.0504]]])
tensor([[[-0.1141,  0.3403],
         [ 1.2995, -0.2421],
         [ 0.6156, -0.6098],
         [ 1.2012, -0.2054],
         [-0.0827, -0.7634]],

        [[ 1.1351, -0.0634],
         [-1.1535,  0.6026],
         [-0.9650, -0.5978],
         [ 0.2094, -0.5810],
         [ 1.0234,  0.2286]],

        [[-1.5108, -0.7440],
         [ 0.9855,  1.5039],
         [ 0.3154, -0.2467],
         [ 0.2673, -1.2389],
         [ 1.0570,  1.2580]]])
tensor([[[ 4.4646, -0.6036],
         [ 0.6927, -

# Tensor reduction

In [24]:
a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


# Transpose

In [31]:
a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


# Bilinear transformation

In [32]:
a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[-1.0398, -0.0277, -1.4539],
        [ 2.3286,  0.2773,  0.1847]])
tensor([[[-1.9473, -0.7830, -0.3186,  0.2888],
         [ 0.3462,  1.7144, -0.1409, -1.8719],
         [ 0.3154, -1.0503,  0.5024, -0.7901]],

        [[-0.4666,  1.1429,  1.2826,  0.0789],
         [ 0.9225, -1.4927,  0.6351, -0.5602],
         [-0.0954,  0.4608, -0.5915,  0.9831]],

        [[-0.6762, -1.7044, -1.1853,  0.6254],
         [ 1.0133, -2.1496,  1.2599, -0.7597],
         [-0.8118,  0.1142, -0.8986,  0.1337]]])
tensor([[-0.5186, -0.7824, -1.7112,  1.4743],
        [-0.0416,  0.8856,  0.6247, -0.0125]])
tensor([[-0.5983, -0.2532, -7.7644],
        [-1.6134,  4.0059, -5.5894]])


# Attention

In [33]:
def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors
bM, br, w = random_tensors([7], num=3, requires_grad=True)
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])
  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at
Y = torch.randn(3,5,7)
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.1610, 0.0267, 0.6410, 0.1368, 0.0345],
        [0.3120, 0.1405, 0.2352, 0.0782, 0.2341],
        [0.6287, 0.0624, 0.0550, 0.0322, 0.2216]], grad_fn=<SoftmaxBackward0>)


<ipython-input-33-7de9fe594675>:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


# Treeqn

In [34]:
def transition(zl):
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)
zl = torch.randn(2, 3)
b = torch.randn(5, 3)
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[ 0.0906, -0.1373, -1.3560],
         [-1.3797,  0.6889, -0.2883],
         [ 0.0166, -0.6216,  0.5134],
         [-1.6399,  1.0142, -0.7237],
         [-0.1018, -0.7245, -0.3301]],

        [[-1.7863, -2.5117, -0.4432],
         [-1.1353, -0.5883,  1.4673],
         [-1.7590, -2.2952,  1.5078],
         [-0.8271, -0.5944,  0.2364],
         [-0.6205, -1.8291,  0.2456]]])