<a href="https://colab.research.google.com/github/ChirudeepG/CMPE-258-Assignment2/blob/main/2B_using_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.random.normal([2])
b = tf.random.normal([4, 5])
mult = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(mult)

tf.Tensor([ 1.4897943 -1.1748651], shape=(2,), dtype=float32)
tf.Tensor(
[[-0.40116578  0.38682494  0.17673711 -1.2007526   0.79707456]
 [-1.4183741   0.45510516  0.02622974  3.0723755  -1.2560861 ]
 [-0.5424445  -1.2664225  -0.21043049 -0.79208803 -0.6240281 ]
 [ 0.45787165  0.65279037  1.1282362  -0.20572892  2.105647  ]], shape=(4, 5), dtype=float32)
tf.Tensor(
[[-0.1263388   0.12182244  0.05565967 -0.37815198  0.25102198]
 [-0.4466873   0.14332587  0.00826051  0.96758056 -0.39557812]
 [-0.17083158 -0.39883333 -0.06627069 -0.2494516  -0.19652462]
 [ 0.14419712  0.20558271  0.35531443 -0.06479003  0.6631296 ]], shape=(4, 5), dtype=float32)


# Vector vector multiplication

In [3]:
a = tf.random.normal([3, 6])
b = tf.random.normal([6, 4])
mult = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

tf.Tensor(
[[ 0.32306722 -0.18537551 -0.4724793   0.225053   -1.4052966  -0.42374587]
 [ 0.54405564 -0.0844814  -0.40284812  0.20447113 -1.6826541   0.47651416]
 [-0.66700053 -0.536485   -1.6320355  -0.50667334  0.25962985  2.2471309 ]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[ 1.1100532  -0.36126894 -0.92321265  1.0629514 ]
 [-1.2417707   0.24940212  0.55500406 -1.0865283 ]
 [ 0.80707324 -1.332068   -1.3956316   0.01812829]
 [ 1.1491086  -1.0019308   0.26604718 -1.2544038 ]
 [ 0.90796083  0.6200239   0.8441721  -0.03532929]
 [-0.14513102  2.0127769  -0.5451826  -1.520093  ]], shape=(6, 4), dtype=float32)
tf.Tensor(
[[-0.74835503 -1.4832836  -0.6371554   0.9477291 ]
 [-0.97827214  0.02996576 -1.612777   -0.258595  ]
 [-2.064004    7.472749    1.4550289  -2.9451165 ]], shape=(3, 4), dtype=float32)


# Outer product

In [4]:
a = tf.range(5)
b = tf.range(2, 6)  
prod = tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor(
[[ 0  0  0  0]
 [ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]], shape=(5, 4), dtype=int32)


# Scalar dot product

In [6]:
a = tf.range(9)
a = tf.reshape(a, [3, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

prod = tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(204, shape=(), dtype=int32)


# Hadamard product

In [9]:
a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

prod = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


# Batch matrix multiplication



In [14]:
a = tf.random.normal([3, 4, 4])
b = tf.random.normal([3, 4, 4])
batch_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

tf.Tensor(
[[[-0.4574606   0.17234048 -1.2353694   0.07536527]
  [ 0.10458714 -0.3633794  -1.2641603  -0.11474583]
  [-0.86359936 -0.7911325  -0.03576707  0.6501386 ]
  [-0.2698698   0.5830658   0.27838397  0.03318968]]

 [[-1.8916273   0.54657894  1.1253119   2.0036027 ]
  [ 0.7496654  -1.298532    0.31670547 -0.7526369 ]
  [-3.272598    0.5489559  -2.2832375   1.2624373 ]
  [ 0.5757006   0.56993073 -2.0965347  -0.28902477]]

 [[-0.11277851 -0.60545987 -1.8494831   0.9527181 ]
  [-0.16950656 -0.8912583  -0.3203133  -0.49128297]
  [-1.6056501   0.4030037  -1.0536739   0.1971661 ]
  [ 0.62148464  0.1492531  -0.05015562  0.64526975]]], shape=(3, 4, 4), dtype=float32)
tf.Tensor(
[[[-1.0964999  -0.33527336  1.0389693  -0.04578558]
  [-0.29479122 -1.0236908  -0.0290921   0.7950204 ]
  [ 0.70197296 -1.1568508   0.95371866  1.136642  ]
  [ 0.41394496 -0.62055326  0.621883    0.19299506]]

 [[ 0.1375564  -0.11231506  2.3248186  -0.42641497]
  [-0.29666048  0.34169146 -0.76754713  0.26789144]
 

# Tensor reduction



In [18]:
a = tf.random.normal([2, 3, 5, 7])
b = tf.random.normal([4, 1, 3, 11, 5])
reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


# Transpose

In [22]:
a = tf.range(8)
a = tf.reshape(a, [4, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6]
 [1 3 5 7]], shape=(2, 4), dtype=int32)


# Bilinear transformation

In [23]:
a = tf.random.normal([2, 3])
b = tf.random.normal([3, 3, 4])
c = tf.random.normal([2, 4])
bilinear = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

tf.Tensor(
[[-0.35930634 -1.250925   -0.5186949 ]
 [ 0.84256834 -0.09247732 -0.05536413]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[-0.6104283   1.2481927  -0.5915614   0.6860771 ]
  [-0.6456257   0.4051475   0.24062672  0.2963591 ]
  [-0.2844441  -2.6942496  -0.51876074  0.05682862]]

 [[ 0.2425737   0.41953266 -0.67480063 -0.80366373]
  [-1.1917937   0.90725046 -0.51389843 -0.18593773]
  [-1.0136105   1.2020969  -1.3366598   0.84027594]]

 [[-2.271639    0.2520425   1.2846333  -1.5649188 ]
  [ 2.062921    0.7518206  -0.8873531   0.2025963 ]
  [-1.8807793   0.71498406 -0.74577415  1.131761  ]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[ 0.7309487  -0.44401228 -0.5143638   1.328198  ]
 [-0.01878936 -1.2040316   0.96005756 -1.5518479 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.28971112  1.5595987  -0.8561009 ]
 [-2.7144778   0.4157254   3.243355  ]], shape=(2, 3), dtype=float32)


#Attention

In [24]:
bM = tf.random.normal([7])
br = tf.random.normal([7]) 
w = tf.random.normal([7])
WY = tf.random.normal([7, 7])
Wh = tf.random.normal([7, 7])
Wr = tf.random.normal([7, 7])
Wt = tf.random.normal([7, 7])

def attention(Y, ht, rt1): 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at
Y = tf.random.normal([3,5,7])
ht = tf.random.normal([3, 7])
rt1 = tf.random.normal([3, 7])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[4.3781173e-01 4.6169737e-01 9.9337876e-02 7.6900847e-04 3.8408276e-04]
 [6.3691795e-02 1.4779721e-03 2.6286913e-03 2.1490805e-02 9.1071075e-01]
 [3.4938163e-01 1.5173681e-01 8.4784359e-02 2.3056918e-01 1.8352799e-01]], shape=(3, 5), dtype=float32)


# Treeqn

In [25]:
def transition(zl):
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)
zl = tf.random.normal([2, 3])
b = tf.random.normal([5, 3])
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[-1.5490136 ,  0.98833334, -0.85156745],
        [-0.3282224 , -0.13758643, -1.5673225 ],
        [-2.3149867 , -0.4818615 , -1.4423692 ],
        [-0.33510405, -0.966508  , -1.4038703 ],
        [-2.3228185 ,  0.45530856,  0.32462722]],

       [[-1.7028899 ,  1.2440329 ,  2.4835205 ],
        [ 0.0331493 , -0.0188576 ,  2.3562121 ],
        [-0.5034164 ,  1.647627  ,  1.0776937 ],
        [ 0.23467243,  0.9292601 ,  1.1996545 ],
        [-1.7019521 ,  1.329395  ,  0.7620082 ]]], dtype=float32)>